spring.application.name=PencilDrive
spring.mvc.view.prefix = /templates
spring.mvc.view.suffix = .html
spring.datasource.url = jdbc:mysql://localhost:3306/filedrive
spring.datasource.username = app
spring.datasource.password = Hello@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
javax.xml.bind:jaxb-api
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret = PencilDriverrrrrrrrrrrrrrrrrrrrrrr2026@!#50*%12secr
jwt.expiration = 864000000

# Set maximum size for a single file (e.g., 50 Megabytes)
spring.servlet.multipart.max-file-size=50MB
# Set maximum size for the entire request (useful if uploading multiple files)
spring.servlet.multipart.max-request-size=50MB
pencildrive.storage.local-path=D:/PencilDriveStorage
spring.datasource.hikari.maximum-pool-size = 80



